keys:
  # admins
  - &user_gajdos "age1sw6plpp4f4anl7alfsflnrj5p5ll8qk8z4yugn3fsy0xqaakmcyq0nzlxt"
  - &user_thinkpad "age19354e8dk6na0k23mq9ea3lz5pdwk30yph4mqg7xvknqk9w5p8pjquwxgnl"
  - &user_shathak "age1rm5ssrnu95mxw5k5m3jx3l7cd0ykfdltfn25lvyukh4hggej6ygq7k842j"
  - &user_nixodeos "age16cplnuasf0m5nn25ukxks4a9ws97cvqllfe3n929xvjtylv6qucsqmu9s6"
  # hosts
  - &host_gajdos "age1ggqwgf3tcyxnxzkxhykl0hma3m4kp9vjx62x05x60zltfapnu48s5whjpr"
  - &host_thinkpad "age1xu76dawvwg68vvclpccsdz5lsczpwpwfc7tvy3s4xvydv8mhk3dsxy09n2"
  - &host_shathak "age18unhxeh8wswd06t9mwp34v9fm9cqwtaw9lhkf0kev02r76n9n58st4qkry"
  - &host_nixodeos "age1j3vt8tgwpzvxx6l3atjed02qxxe8lpglegn0w95l2t6xwkds03xqvyma0w"

creation_rules:
  - path_regex: secrets/server/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_nixodeos
          - *host_nixodeos
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_gajdos
          - *user_thinkpad
          - *user_shathak
          - *user_nixodeos
          - *host_gajdos
          - *host_thinkpad
          - *host_shathak
          - *host_nixodeos
