# https://wiki.hyprland.org/Configuring/

source = env.conf
source = monitors.conf
source = autostart.conf
source = binds.conf
source = input.conf
source = eyecandy.conf
source = rules.conf
source = layout.conf

source = workaround/reaper.conf

misc {
    #enable_swallow = true
    swallow_regex = Alacritty
}

binds {
  movefocus_cycles_fullscreen = false
}
