# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [
    "btrfs"
    "ext4"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bf4c6d39-f05d-40e9-9079-7c8c593a19de";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8749-E3F9";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home/media" = {
    device = "/dev/mapper/vg0-media";
    fsType = "ext4";
  };

  fileSystems."/home/virt" = {
    device = "/dev/mapper/vg0-virt";
    fsType = "ext4";
  };

  fileSystems."/home/data" =
    #{ device = "/dev/mapper/vg0-data";
    {
      device = "/dev/disk/by-uuid/8e7e3c81-a5f2-4b80-ad2f-1cb52c872bf5";
      fsType = "btrfs";
      options = [ "nofail" ];
    };

  fileSystems."/home/steam" = {
    device = "/dev/mapper/vg0-steam";
    fsType = "ext4";
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/vg0-nix";
    fsType = "ext4";
    neededForBoot = true;
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
